CREATE TABLE `rent_users` (
	`id` INT(10) NOT NULL AUTO_INCREMENT,
	`login` VARCHAR(50) NOT NULL DEFAULT '',
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`info` VARCHAR(255) NULL DEFAULT NULL,
	`password` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);